version: "2"
run:
  tests: true
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - all
        path: zz_generated.*\.go
      - linters:
          - all
        path: _mock\.go
    paths:
      - bin
      - headlamp-plugin/node_modules
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/dsx-ai-factory/workload-map
  exclusions:
    generated: lax
    paths:
      - bin
      - headlamp-plugin/node_modules
      - vendor
      - third_party$
      - builtin$
      - examples$
