# This file was generated by GoReleaser. DO NOT EDIT.
cask "kli" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kli"]
    end
  end

  version "0.3.1001"

  on_macos do
    on_arm do
      sha256 "7c7e3a8ec4bbbc93bf7e4a56af3eeb1767642d0dd9ee5360b7e674b80d21c80c"
      url "https://github.com/shaked-bouktus/karta/releases/download/v#{version}/karta_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "247471c5c5117c585a40e0a232969cbe5f0afe18136bcd585cc543030c1897cd"
      url "https://github.com/shaked-bouktus/karta/releases/download/v#{version}/karta_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "36ee9e1bfa271b274a61775085d374c7345696b66f2fb6de482d966652fbafdf"
      url "https://github.com/shaked-bouktus/karta/releases/download/v#{version}/karta_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d45723d3fcf2acc341adba0538f9f0d4cafab79463c78019eed78322cfb6c49c"
      url "https://github.com/shaked-bouktus/karta/releases/download/v#{version}/karta_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kli"
  desc "Workload-aware visibility for any Kubernetes workload type"
  homepage "https://github.com/shaked-bouktus/karta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kli"

  # No zap stanza required
end
