# This file was generated by GoReleaser. DO NOT EDIT.
cask "kli" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kli"]
    end
  end

  version "0.3.1003"

  on_macos do
    on_arm do
      sha256 "4ce2fcf83527ea26aeade403093e5d42d2706e71a5efcfd5116a092647095913"
      url "https://github.com/shaked-bouktus/karta/releases/download/v#{version}/karta_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "86c7ba9d52fa1ee99d9c8a665cb912f0ab66933ede06f5db27995b805509ced5"
      url "https://github.com/shaked-bouktus/karta/releases/download/v#{version}/karta_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "149d6c8150a4415263cb7659fad5c47c66f3cb09ebeabe27cdad497f963ef197"
      url "https://github.com/shaked-bouktus/karta/releases/download/v#{version}/karta_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f26aa04f6746165df836bb93a1d2ae74a79bed7b5332250f491f0a59a4087571"
      url "https://github.com/shaked-bouktus/karta/releases/download/v#{version}/karta_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kli"
  desc "Workload-aware visibility for any Kubernetes workload type"
  homepage "https://github.com/shaked-bouktus/karta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kli"

  # No zap stanza required
end
