# This file was generated by GoReleaser. DO NOT EDIT.
cask "kli" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kli"]
    end
  end

  version "0.3.1004"

  on_macos do
    on_arm do
      sha256 "cb10d6e7c2b53fc5b81376d9bb20c4478fbe54e666276b06bb6a307fff457e32"
      url "https://github.com/shaked-bouktus/karta/releases/download/v#{version}/karta_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2379a757ba6d3ab4adc9a3d89ba00f0f1932ad7927306695ac3e8918043ee961"
      url "https://github.com/shaked-bouktus/karta/releases/download/v#{version}/karta_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9d6feb6a78cf6d9bfd47616c61c5b1f380c0851aefc9722d2e8706a26f819d94"
      url "https://github.com/shaked-bouktus/karta/releases/download/v#{version}/karta_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "97ab204a3a51d3715a5ea0e82450cad4d428214f3effdec3171124d25558d228"
      url "https://github.com/shaked-bouktus/karta/releases/download/v#{version}/karta_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kli"
  desc "Workload-aware visibility for any Kubernetes workload type"
  homepage "https://github.com/shaked-bouktus/karta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kli"

  # No zap stanza required
end
