# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
kind: Karta
apiVersion: run.ai/v1alpha1
metadata:
  name: apps-nvidia-com-nimservice-v1alpha1
spec:
  structureDefinition:
    rootComponent:
      name: nimservice
      kind:
        group: apps.nvidia.com
        version: v1alpha1
        kind: NIMService
      specDefinition:
        fragmentedPodSpecDefinition:
          schedulerNamePath: .spec.schedulerName
          labelsPath: .spec.labels
          annotationsPath: .spec.annotations
          resourcesPath: .spec.resources
          podAffinityPath: .spec.affinity.podAffinity
          nodeAffinityPath: .spec.affinity.nodeAffinity
      scaleDefinition:
        replicasPath: .spec.replicas // 1
      statusDefinition:
        phaseDefinition:
          path: .status.state
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          messageFieldName: message
        statusMappings:
          initializing:
            - byExpression:
                expression: (.status.state // "") != "Ready" and (.status.state // "") != "Failed"
                expectedResult: "true"
          running:
            - byPhase: Ready
          failed:
            - byPhase: Failed
  optimizationInstructions:
    gangScheduling:
      podGroups:
        - name: service
          members:
            - componentName: nimservice
              groupByKeyPaths:
                - .metadata.labels["app.kubernetes.io/name"]
