# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
kind: Karta
apiVersion: run.ai/v1alpha1
metadata:
  name: apps-deployment-v1
spec:
  structureDefinition:
    rootComponent:
      name: deployment
      kind:
        group: apps
        version: v1
        kind: Deployment
      specDefinition:
        podTemplateSpecPath: .spec.template
      scaleDefinition:
        replicasPath: .spec.replicas // 1
      statusDefinition:
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          messageFieldName: message
          reasonFieldName: reason
        statusMappings:
          initializing:
            - byExpression:
                expression: (([.status.conditions[]? | select(.type == "Progressing" and .status == "True")] | length) > 0) and (([.status.conditions[]? | select(.type == "Available" and .status == "True")] | length) == 0)
                expectedResult: "true"
          running:
            - byConditions:
                - type: Progressing
                  status: "True"
                  reason: NewReplicaSetAvailable
          failed:
            - byConditions:
                - type: Progressing
                  status: "False"
                  reason: ProgressDeadlineExceeded
    childComponents:
      - name: replicaset
        kind:
          group: apps
          version: v1
          kind: ReplicaSet
        ownerRef: deployment
  optimizationInstructions: {}
