# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
kind: Karta
apiVersion: run.ai/v1alpha1
metadata:
  name: leaderworkerset-x-k8s-io-leaderworkerset-v1
spec:
  structureDefinition:
    rootComponent:
      name: leaderworkerset
      kind:
        group: leaderworkerset.x-k8s.io
        version: v1
        kind: LeaderWorkerSet
      statusDefinition:
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          messageFieldName: message
        statusMappings:
          initializing:
            - byExpression:
                expression: (([.status.conditions[]? | select(.type == "Progressing" and .status == "True")] | length) > 0) and (([.status.conditions[]? | select(.type == "Available" and .status == "True")] | length) == 0)
                expectedResult: "true"
          running:
            - byConditions:
                - type: Available
                  status: "True"
            - byExpression:
                expression: (.status.replicas // 0) > 0 and .status.readyReplicas == .status.replicas and .status.updatedReplicas == .status.replicas
                expectedResult: "true"
          failed:
            - byConditions:
                - type: Available
                  status: "False"
                - type: Progressing
                  status: "False"
                - type: UpdateInProgress
                  status: "False"
    childComponents:
      - name: group
        ownerRef: leaderworkerset
        scaleDefinition:
          replicasPath: .spec.leaderWorkerTemplate.size
        podSelector:
          replicaSelector:
            keyPath: .metadata.labels["leaderworkerset.sigs.k8s.io/group-index"]
      - name: leader
        kind:
          group: apps
          version: v1
          kind: StatefulSet
        ownerRef: group
        specDefinition:
          podTemplateSpecPath: .spec.leaderWorkerTemplate.leaderTemplate
        scaleDefinition:
          replicasPath: .spec.replicas // 1
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["leaderworkerset.sigs.k8s.io/worker-index"]
            value: "0"
      - name: worker
        kind:
          group: apps
          version: v1
          kind: StatefulSet
        ownerRef: group
        specDefinition:
          podTemplateSpecPath: .spec.leaderWorkerTemplate.workerTemplate
        scaleDefinition:
          replicasPath: (.spec.replicas // 1) * ((.spec.leaderWorkerTemplate.size // 1) - 1)
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.annotations["leaderworkerset.sigs.k8s.io/leader-name"]
  optimizationInstructions:
    gangScheduling:
      podGroups:
        - name: group
          members:
            - componentName: group
              groupByKeyPaths:
                - .metadata.labels["leaderworkerset.sigs.k8s.io/name"]
                - .metadata.labels["leaderworkerset.sigs.k8s.io/group-index"] // "0"
