# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
kind: Karta
apiVersion: run.ai/v1alpha1
metadata:
  name: milvus-io-milvus-v1beta1
spec:
  structureDefinition:
    rootComponent:
      name: milvus
      kind:
        group: milvus.io
        version: v1beta1
        kind: Milvus
      statusDefinition:
        phaseDefinition:
          path: .status.status
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
        statusMappings:
          initializing:
            - byPhase: Pending
            - byExpression:
                expression: (.status.status // "") == ""
                expectedResult: "true"
          running:
            - byPhase: Healthy
          degraded:
            - byPhase: Unhealthy
    childComponents:
      - name: standalone
        kind:
          group: apps
          version: v1
          kind: Deployment
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components.standalone.schedulerName
            labelsPath: .spec.components.standalone.podLabels
            annotationsPath: .spec.components.standalone.podAnnotations
            resourcesPath: .spec.components.standalone.resources
            podAffinityPath: .spec.components.standalone.affinity.podAffinity
            nodeAffinityPath: .spec.components.standalone.affinity.nodeAffinity
            priorityClassNamePath: .spec.components.standalone.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components.standalone.replicas
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["app.kubernetes.io/component"]
            value: standalone
      - name: proxy
        kind:
          group: apps
          version: v1
          kind: Deployment
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components.proxy.schedulerName
            labelsPath: .spec.components.proxy.podLabels
            annotationsPath: .spec.components.proxy.podAnnotations
            resourcesPath: .spec.components.proxy.resources
            podAffinityPath: .spec.components.proxy.affinity.podAffinity
            nodeAffinityPath: .spec.components.proxy.affinity.nodeAffinity
            priorityClassNamePath: .spec.components.proxy.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components.proxy.replicas
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["app.kubernetes.io/component"]
            value: proxy
      - name: mixcoord
        kind:
          group: apps
          version: v1
          kind: Deployment
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components.mixCoord.schedulerName
            labelsPath: .spec.components.mixCoord.podLabels
            annotationsPath: .spec.components.mixCoord.podAnnotations
            resourcesPath: .spec.components.mixCoord.resources
            podAffinityPath: .spec.components.mixCoord.affinity.podAffinity
            nodeAffinityPath: .spec.components.mixCoord.affinity.nodeAffinity
            priorityClassNamePath: .spec.components.mixCoord.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components.mixCoord.replicas
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["app.kubernetes.io/component"]
            value: mixcoord
      - name: datanode
        kind:
          group: apps
          version: v1
          kind: Deployment
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components.dataNode.schedulerName
            labelsPath: .spec.components.dataNode.podLabels
            annotationsPath: .spec.components.dataNode.podAnnotations
            resourcesPath: .spec.components.dataNode.resources
            podAffinityPath: .spec.components.dataNode.affinity.podAffinity
            nodeAffinityPath: .spec.components.dataNode.affinity.nodeAffinity
            priorityClassNamePath: .spec.components.dataNode.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components.dataNode.replicas
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["app.kubernetes.io/component"]
            value: datanode
      - name: querynode
        kind:
          group: apps
          version: v1
          kind: Deployment
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components.queryNode.schedulerName
            labelsPath: .spec.components.queryNode.podLabels
            annotationsPath: .spec.components.queryNode.podAnnotations
            resourcesPath: .spec.components.queryNode.resources
            podAffinityPath: .spec.components.queryNode.affinity.podAffinity
            nodeAffinityPath: .spec.components.queryNode.affinity.nodeAffinity
            priorityClassNamePath: .spec.components.queryNode.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components.queryNode.replicas
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["app.kubernetes.io/component"]
            value: querynode
      - name: streamingnode
        kind:
          group: apps
          version: v1
          kind: Deployment
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components.streamingNode.schedulerName
            labelsPath: .spec.components.streamingNode.podLabels
            annotationsPath: .spec.components.streamingNode.podAnnotations
            resourcesPath: .spec.components.streamingNode.resources
            podAffinityPath: .spec.components.streamingNode.affinity.podAffinity
            nodeAffinityPath: .spec.components.streamingNode.affinity.nodeAffinity
            priorityClassNamePath: .spec.components.streamingNode.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components.streamingNode.replicas
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["app.kubernetes.io/component"]
            value: streamingnode
      - name: indexnode
        kind:
          group: apps
          version: v1
          kind: Deployment
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components.indexNode.schedulerName
            labelsPath: .spec.components.indexNode.podLabels
            annotationsPath: .spec.components.indexNode.podAnnotations
            resourcesPath: .spec.components.indexNode.resources
            podAffinityPath: .spec.components.indexNode.affinity.podAffinity
            nodeAffinityPath: .spec.components.indexNode.affinity.nodeAffinity
            priorityClassNamePath: .spec.components.indexNode.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components.indexNode.replicas
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["app.kubernetes.io/component"]
            value: indexnode
      - name: rootcoord
        kind:
          group: apps
          version: v1
          kind: Deployment
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components.rootCoord.schedulerName
            labelsPath: .spec.components.rootCoord.podLabels
            annotationsPath: .spec.components.rootCoord.podAnnotations
            resourcesPath: .spec.components.rootCoord.resources
            podAffinityPath: .spec.components.rootCoord.affinity.podAffinity
            nodeAffinityPath: .spec.components.rootCoord.affinity.nodeAffinity
            priorityClassNamePath: .spec.components.rootCoord.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components.rootCoord.replicas
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["app.kubernetes.io/component"]
            value: rootcoord
      - name: datacoord
        kind:
          group: apps
          version: v1
          kind: Deployment
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components.dataCoord.schedulerName
            labelsPath: .spec.components.dataCoord.podLabels
            annotationsPath: .spec.components.dataCoord.podAnnotations
            resourcesPath: .spec.components.dataCoord.resources
            podAffinityPath: .spec.components.dataCoord.affinity.podAffinity
            nodeAffinityPath: .spec.components.dataCoord.affinity.nodeAffinity
            priorityClassNamePath: .spec.components.dataCoord.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components.dataCoord.replicas
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["app.kubernetes.io/component"]
            value: datacoord
      - name: querycoord
        kind:
          group: apps
          version: v1
          kind: Deployment
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components.queryCoord.schedulerName
            labelsPath: .spec.components.queryCoord.podLabels
            annotationsPath: .spec.components.queryCoord.podAnnotations
            resourcesPath: .spec.components.queryCoord.resources
            podAffinityPath: .spec.components.queryCoord.affinity.podAffinity
            nodeAffinityPath: .spec.components.queryCoord.affinity.nodeAffinity
            priorityClassNamePath: .spec.components.queryCoord.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components.queryCoord.replicas
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["app.kubernetes.io/component"]
            value: querycoord
      - name: indexcoord
        kind:
          group: apps
          version: v1
          kind: Deployment
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components.indexCoord.schedulerName
            labelsPath: .spec.components.indexCoord.podLabels
            annotationsPath: .spec.components.indexCoord.podAnnotations
            resourcesPath: .spec.components.indexCoord.resources
            podAffinityPath: .spec.components.indexCoord.affinity.podAffinity
            nodeAffinityPath: .spec.components.indexCoord.affinity.nodeAffinity
            priorityClassNamePath: .spec.components.indexCoord.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components.indexCoord.replicas
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["app.kubernetes.io/component"]
            value: indexcoord
      - name: cdc
        kind:
          group: apps
          version: v1
          kind: Deployment
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components.cdc.schedulerName
            labelsPath: .spec.components.cdc.podLabels
            annotationsPath: .spec.components.cdc.podAnnotations
            resourcesPath: .spec.components.cdc.resources
            podAffinityPath: .spec.components.cdc.affinity.podAffinity
            nodeAffinityPath: .spec.components.cdc.affinity.nodeAffinity
            priorityClassNamePath: .spec.components.cdc.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components.cdc.replicas
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["app.kubernetes.io/component"]
            value: cdc
      - name: etcd
        kind:
          group: apps
          version: v1
          kind: StatefulSet
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            resourcesPath: .spec.dependencies.etcd.inCluster.values.resources
        scaleDefinition:
          replicasPath: .spec.dependencies.etcd.inCluster.values.replicaCount
      - name: minio
        kind:
          group: apps
          version: v1
          kind: StatefulSet
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            resourcesPath: .spec.dependencies.storage.inCluster.values.resources
      - name: pulsar-zookeeper
        kind:
          group: apps
          version: v1
          kind: StatefulSet
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            resourcesPath: .spec.dependencies.pulsar.inCluster.values.zookeeper.resources
        scaleDefinition:
          replicasPath: .spec.dependencies.pulsar.inCluster.values.zookeeper.replicaCount
      - name: pulsar-bookkeeper
        kind:
          group: apps
          version: v1
          kind: StatefulSet
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            resourcesPath: .spec.dependencies.pulsar.inCluster.values.bookkeeper.resources
        scaleDefinition:
          replicasPath: .spec.dependencies.pulsar.inCluster.values.bookkeeper.replicaCount
      - name: pulsar-broker
        kind:
          group: apps
          version: v1
          kind: StatefulSet
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            resourcesPath: .spec.dependencies.pulsar.inCluster.values.broker.resources
        scaleDefinition:
          replicasPath: .spec.dependencies.pulsar.inCluster.values.broker.replicaCount
      - name: pulsar-proxy
        kind:
          group: apps
          version: v1
          kind: StatefulSet
        ownerRef: milvus
        specDefinition:
          fragmentedPodSpecDefinition:
            resourcesPath: .spec.dependencies.pulsar.inCluster.values.proxy.resources
        scaleDefinition:
          replicasPath: .spec.dependencies.pulsar.inCluster.values.proxy.replicaCount
  optimizationInstructions:
    gangScheduling:
      podGroups:
        - name: cluster
          members:
            - componentName: querynode
              groupByKeyPaths:
                - .metadata.labels["app.kubernetes.io/instance"]
            - componentName: datanode
              groupByKeyPaths:
                - .metadata.labels["app.kubernetes.io/instance"]
            - componentName: streamingnode
              groupByKeyPaths:
                - .metadata.labels["app.kubernetes.io/instance"]
