# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
kind: Karta
apiVersion: run.ai/v1alpha1
metadata:
  name: ray-io-rayjob-v1
spec:
  structureDefinition:
    rootComponent:
      name: rayjob
      kind:
        group: ray.io
        version: v1
        kind: RayJob
      statusDefinition:
        phaseDefinition:
          path: .status.jobStatus
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          messageFieldName: message
        statusMappings:
          initializing:
            - byPhase: PENDING
            - byExpression:
                expression: (.status.jobStatus // "") == "" and (.status.jobDeploymentStatus // "") != "Suspended" and (.status.jobDeploymentStatus // "") != "Suspending"
                expectedResult: "true"
          running:
            - byPhase: RUNNING
          completed:
            - byPhase: SUCCEEDED
          failed:
            - byPhase: FAILED
          suspended:
            - byExpression:
                expression: .status.jobDeploymentStatus == "Suspended" or .status.jobDeploymentStatus == "Suspending"
                expectedResult: "true"
      suspendDefinition:
        suspendActions:
          - path: .spec.suspend
            value: "true"
        resumeActions:
          - path: .spec.suspend
            value: "false"
    childComponents:
      - name: head
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: rayjob
        specDefinition:
          podTemplateSpecPath: .spec.rayClusterSpec.headGroupSpec.template
        scaleDefinition:
          replicasPath: "1"
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["ray.io/node-type"]
            value: head
      - name: worker
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: rayjob
        specDefinition:
          podTemplateSpecPath: .spec.rayClusterSpec.workerGroupSpecs[].template
        scaleDefinition:
          replicasPath: .spec.rayClusterSpec.workerGroupSpecs[].replicas // 1
          minReplicasPath: .spec.rayClusterSpec.workerGroupSpecs[].minReplicas
          maxReplicasPath: .spec.rayClusterSpec.workerGroupSpecs[].maxReplicas
        instanceIdPath: .spec.rayClusterSpec.workerGroupSpecs[].groupName
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["ray.io/node-type"]
            value: worker
          componentInstanceSelector:
            idPath: .metadata.labels["ray.io/group"]
  optimizationInstructions:
    gangScheduling:
      podGroups:
        - name: job
          members:
            - componentName: head
              groupByKeyPaths:
                - .metadata.labels["ray.io/cluster"]
            - componentName: worker
              groupByKeyPaths:
                - .metadata.labels["ray.io/cluster"]
